buildscript {
    repositories {
	    maven { url 'https://maven.myket.ir/' }
		google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.myket.ir/' }
        google()
        mavenCentral()
    }
}